[build]
  publish = "client/build"
  command = "npm run build --prefix client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  HTTP_PROXY = "https://acm-web-sqiv.onrender.com"
  HTTPS_PROXY = "https://acm-web-sqiv.onrender.com"

