export const ProfileActionTypes = {
  FETCH_PROFILE_START: "FETCH_PROFILE_START",
  FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
  UPDATE_PROFILE_START: "UPDATE_PROFILE_START",
  UPDATE_PROFILE_COMPLETE: "UPDATE_PROFILE_COMPLETE",
  ACCOUNT_DELETE: "ACCOUNT_DELETE",
  PROFILE_ERROR: "PROFILE_ERROR",
  LOGOUT: "LOGOUT",
};
