export const applicationActionTypes = {
  FETCH_ALL_APPLICATIONS_START: "FETCH_ALL_APPLICATIONS_START",
  FETCH_ALL_APPLICATIONS_SUCCESS: "FETCH_ALL_APPLICATIONS_SUCCESS",
  NO_APPLICATIONS: "NO_APPLICATIONS",
};
