export const applicationActionTypes = {
  FETCH_ALL_APPLICATIONS_START: "FETCH_ALL_APPLICATIONS_START",
  FETCH_ALL_APPLICATIONS_SUCCESS: "FETCH_ALL_APPLICATIONS_SUCCESS",
  APPROVE_APPLICATION: "APPROVE_APPLICATION",
  REJECT_APPLICATION: "REJECT_APPLICATION",
  NO_APPLICATIONS: "NO_APPLICATIONS",
};
